#!/bin/bash
export CAP_SOLACE="s"
export SOL_USR="s"
export SOL_PWD="s"
export FIXTURE_ENDPOINT="s"
export SSL_TRUST_STORE="s"
export SSL_TRUST_STORE_FORMAT="s"
export SSL_TRUST_STORE_PASSWORD="s"
export FILE_ROOT_PATH="s"
export MAPRDB_HOSTNAME="s"
export MAPRDB_PORT="s"
export MAPRDB_USER="s"
export MAPRDB_CERT_PATH="s"
export MAPRDB_NODE_FQDN="s"